const token=localStorage.getItem("sensiFF_token");if(!token)location.href="index.html";
async function apiP(p,o={}){o.headers={...(o.headers||{}),Authorization:"Bearer "+token};const r=await fetch(API_BASE+p,o);let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.erro||"Erro");return d}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
async function load(){try{const d=await apiP("/api/auth/me"),u=d.usuario;userName.textContent=u.nome;topUser.textContent=u.email;saldo.textContent=money(u.saldo);plano.textContent=u.planoVIP?"VIP Ativo":"Gratuito";vipChip.textContent=u.planoVIP?"◆ VIP ATIVO":"◇ GRATUITO";const h=await apiP("/api/sensibilidade/historico");geracoes.textContent=h.historico.length;history.innerHTML=h.historico.length?h.historico.slice(0,6).map(x=>`<div class="history-row"><span>${x.aparelho}</span><b>${x.pagoCom}</b></div>`).join(""):"<div class='empty'>Nenhuma geração ainda.</div>"}catch(e){localStorage.removeItem("sensiFF_token");location.href="index.html"}}
async function generate(){try{generateBtn.disabled=true;generateBtn.textContent="Calculando...";const d=await apiP("/api/sensibilidade/gerar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({marca:marca.value,modelo:modelo.value,estilo:estilo.value})});const s=d.sensibilidade.sensibilidadeJogo;deviceTitle.textContent=d.dadosAparelho.marca+" "+d.dadosAparelho.modelo;resultEmpty.classList.add("hidden");result.classList.remove("hidden");result.innerHTML=Object.entries(s).map(([k,v])=>`<div class="sens-row"><span>${k}</span><b>${v}</b><i><u style="width:${Math.min(100,v)}%"></u></i></div>`).join("")+`<div class="system-box"><b>DPI</b><strong>${d.sensibilidade.configuracoesSistema.dpi}</strong><b>Botão</b><strong>${d.sensibilidade.configuracoesSistema.tamanhoBotaoAtirar}</strong></div>`;saldo.textContent=money(d.pagamento.saldoRestante);load()}catch(e){alert(e.message)}finally{generateBtn.disabled=false;generateBtn.textContent="Gerar sensibilidade ✦"}}
async function createPix(){try{const d=await apiP("/api/pix/criar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({valor:Number(pixValue.value)})});pixBox.classList.remove("hidden");pixBox.innerHTML=`<div class="pix-card">${d.qrCodeUrl?`<img src="${d.qrCodeUrl}" class="qr">`:""}<p>PIX Copia e Cola</p><textarea readonly>${d.pixCopiaECola||""}</textarea><button class="btn primary full" onclick="navigator.clipboard.writeText(this.previousElementSibling.value);this.textContent='Copiado!'">Copiar código</button><small>Aguardando pagamento...</small></div>`;poll(d.txid)}catch(e){alert(e.message)}}
function poll(id){const t=setInterval(async()=>{try{const d=await apiP("/api/pix/status/"+id);if(d.status==="approved"&&d.creditado){clearInterval(t);alert("PIX confirmado! Saldo atualizado.");load()}}catch{}} ,3000)}
function copyResult(){if(!result.textContent.trim())return;navigator.clipboard.writeText(result.innerText);alert("Resultado copiado.")}
function logout(){localStorage.removeItem("sensiFF_token");location.href="index.html"}load();
